# Numpy

Data structure for Numpy is Array

In [2]:
#importing numpy
import numpy as np

In [3]:
#array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#array of 10 fives
np.ones(10) * 5
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
#array of integers from 10to 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
#array of even integers from 10 to 50
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
#array of odd integers from 10to 50
np.arange(11, 51, 2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [9]:
#3X3 matrix with in value ranging from 0 to 8
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#3X3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#random number between 0 to 1
np.random.rand(1) 

array([0.26884869])

In [12]:
np.random.randint(15) #random integer

1

In [13]:
#create 25 random sample from standard normal distribution
np.random.randn(25) 

array([ 1.04103335,  0.18437462,  0.20853035,  1.70289997, -0.95642057,
       -0.31451722, -1.08519479, -1.78107239,  1.33826008, -0.56035714,
        1.63561156, -0.05842232,  0.49505335, -0.0116396 , -0.2281862 ,
        0.30307526, -1.83913908, -0.21451778,  1.70740919, -0.65745381,
        0.42954504, -1.15452794, -1.11430376, -1.22993676,  0.08598608])

In [14]:
np.arange(1, 101).reshape(10, 10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [15]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [16]:
#20 linearly spaced points between 0 and 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection


In [17]:
mat = np.arange(0, 25).reshape(5, 5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
#indexing a[row][column]
mat[4][2] #5th row 3rd column as index start from 0 

22

In [19]:
#selecting [from : to: step] index start at from ans stop at to-1
mat[0:3, 0:4:2]

array([[ 0,  2],
       [ 5,  7],
       [10, 12]])

In [20]:
#sum of value in matrix
mat.sum()

300

In [21]:
#standard deviation of mat
np.std(mat)

7.211102550927978

In [22]:
#sum of row of mat
mat.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [23]:
#sum of column of mat
mat.sum(axis = 0)

array([50, 55, 60, 65, 70])

# Pandas and DataFrame

Data structure for Pandas is Dataframe

In [24]:
import pandas as pd
import numpy as np

In [25]:
# creating dataframe using random number => np.random.rand(shape) and 
# assigning index for dataframe
df = pd.DataFrame(np.random.randn(5, 5), [1, 2, 3, 4, 5], ['A', 'B', 'C', 'D', 'E'])
df

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621
4 -0.967945 -0.567608  0.035535  1.464596  0.811468
5 -0.647167 -0.004760  0.919772 -0.231048  0.279118

In [26]:
#acessing or assigning different colums of dataframe
new_df = df['A']
new_df

1    0.538975
2   -0.039392
3   -0.119353
4   -0.967945
5   -0.647167
Name: A, dtype: float64

In [27]:
#new data frame with 2 columns of df
new_df1 = df[['A', 'C']]
new_df1

A         C
1  0.538975  0.119901
2 -0.039392  1.503463
3 -0.119353  0.530754
4 -0.967945  0.035535
5 -0.647167  0.919772

In [28]:
#adding new column 
df['total'] = df['A'] + df['B'] + df['C'] + df['D'] + df['E']

In [29]:
df

A         B         C         D         E     total
1  0.538975  1.605398  0.119901 -0.121957  1.086776  3.229093
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112 -1.285101
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621 -0.493631
4 -0.967945 -0.567608  0.035535  1.464596  0.811468  0.776046
5 -0.647167 -0.004760  0.919772 -0.231048  0.279118  0.315915

In [30]:
#removing column 
df.drop('total', axis = 1) # also change axis: 1 to drop column and 0 to drop row

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621
4 -0.967945 -0.567608  0.035535  1.464596  0.811468
5 -0.647167 -0.004760  0.919772 -0.231048  0.279118

In [31]:
df #doesnt changes on df to prevent acidently losing data so must add argument inplace = True

A         B         C         D         E     total
1  0.538975  1.605398  0.119901 -0.121957  1.086776  3.229093
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112 -1.285101
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621 -0.493631
4 -0.967945 -0.567608  0.035535  1.464596  0.811468  0.776046
5 -0.647167 -0.004760  0.919772 -0.231048  0.279118  0.315915

In [32]:
df.drop('total', axis = 1, inplace= True)

In [33]:
df #now the total column is dropped 

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621
4 -0.967945 -0.567608  0.035535  1.464596  0.811468
5 -0.647167 -0.004760  0.919772 -0.231048  0.279118

In [34]:
#to drop rows
df.drop(5, inplace = True) #axis not required to specify coz default is 0
df

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621
4 -0.967945 -0.567608  0.035535  1.464596  0.811468

In [35]:
df.shape 

(4, 5)

NOTE: Since the shape is in tuple (4, 5) where row is 4 and column is 5 so, the position of row is 0 resulting its axis as 0 similarly column as 1

In [36]:
#acessing or assigning different row of dataframe 
df.loc[1] #we pass 1 as name of index

A    0.538975
B    1.605398
C    0.119901
D   -0.121957
E    1.086776
Name: 1, dtype: float64

So, Both row and columns are series

In [37]:
df.iloc[0] #in iloc we have to pass index of row as argumnet

A    0.538975
B    1.605398
C    0.119901
D   -0.121957
E    1.086776
Name: 1, dtype: float64

In [38]:
df.loc[[1, 4]]

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776
4 -0.967945 -0.567608  0.035535  1.464596  0.811468

In [39]:
#acessing  different rows and column at same time
df.loc[[1, 2, 4], ['A', 'C', 'E']]

A         C         E
1  0.538975  0.119901  1.086776
2 -0.039392  1.503463 -2.054112
4 -0.967945  0.035535  0.811468

In [40]:
booldf = df>0
booldf

A      B     C      D      E
1   True   True  True  False   True
2  False  False  True  False  False
3  False   True  True  False  False
4  False  False  True   True   True

In [41]:
df[booldf]

A         B         C         D         E
1  0.538975  1.605398  0.119901       NaN  1.086776
2       NaN       NaN  1.503463       NaN       NaN
3       NaN  0.126866  0.530754       NaN       NaN
4       NaN       NaN  0.035535  1.464596  0.811468

In [42]:
# dataframe list where A is greater than 0
df[df['A']> 0]

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776

since other row in A have value less than 0 so it is not included


In [44]:
df[df['A']> 0]['B'] # now returns only needed column

1    1.605398
Name: B, dtype: float64

In [45]:
df[df['A']> 0][['B', 'D']]

B         D
1  1.605398 -0.121957

In [51]:
#df[(df['A']> 0) and (df['A']> 0)] raise error since and can only work with single boolean value i.e. True and False
df[(df['A'] < 0) & (df['B'] < 0)]


A         B         C         D         E
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
4 -0.967945 -0.567608  0.035535  1.464596  0.811468

In [52]:
#Reseting index 
df.reset_index()

index         A         B         C         D         E
0      1  0.538975  1.605398  0.119901 -0.121957  1.086776
1      2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
2      3 -0.119353  0.126866  0.530754 -0.242278 -0.789621
3      4 -0.967945 -0.567608  0.035535  1.464596  0.811468

After reseting index previous index will be changed into dataframe and we can drop that previous index

In [53]:
df

A         B         C         D         E
1  0.538975  1.605398  0.119901 -0.121957  1.086776
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621
4 -0.967945 -0.567608  0.035535  1.464596  0.811468

use argumemt inplace =True For permanent change

In [59]:
#creating new column in dataframe
newind = "i ii iii iv".split() 
df[''] = newind # can use variable name in '' aswell
df

A         B         C         D         E     
1  0.538975  1.605398  0.119901 -0.121957  1.086776    i
2 -0.039392 -0.400124  1.503463 -0.294935 -2.054112   ii
3 -0.119353  0.126866  0.530754 -0.242278 -0.789621  iii
4 -0.967945 -0.567608  0.035535  1.464596  0.811468   iv

In [60]:
df.set_index('') #setting new index and use inplace to make permanent changes

A         B         C         D         E
                                                     
i    0.538975  1.605398  0.119901 -0.121957  1.086776
ii  -0.039392 -0.400124  1.503463 -0.294935 -2.054112
iii -0.119353  0.126866  0.530754 -0.242278 -0.789621
iv  -0.967945 -0.567608  0.035535  1.464596  0.811468

In [61]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [62]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -0.669993 -0.972653
   2  0.415593  0.259820
   3  0.160372  0.834462
G2 1 -0.199614 -0.005916
   2  1.357835  0.676535
   3 -0.058807 -1.963789

# Index in multi level index dataframe

In [63]:
df.loc['G1']

A         B
1 -0.669993 -0.972653
2  0.415593  0.259820
3  0.160372  0.834462

In [64]:
df.loc['G1'].loc[2]

A    0.415593
B    0.259820
Name: 2, dtype: float64

In [65]:
df.loc['G1'].loc[2]['B']

0.2598198610746142

# giving name to index

In [69]:
df.index.names

FrozenList(['Group', 'Num'])

In [72]:
df.index.names = ['Group', 'Num']
df

A         B
Group Num                    
G1    1   -0.669993 -0.972653
      2    0.415593  0.259820
      3    0.160372  0.834462
G2    1   -0.199614 -0.005916
      2    1.357835  0.676535
      3   -0.058807 -1.963789

In [71]:
#another method of specifying index
df.xs('G1')

A         B
Num                    
1   -0.669993 -0.972653
2    0.415593  0.259820
3    0.160372  0.834462

In [74]:
df.xs(1, level = 'Num') #get all value of num = 1

A         B
Group                    
G1    -0.669993 -0.972653
G2    -0.199614 -0.005916

In [76]:
df.xs(2, level = 'Num')

A         B
Group                    
G1     0.415593  0.259820
G2     1.357835  0.676535

# Working With missing Data

In [77]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [78]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [79]:
df.dropna()

A    B  C
0  1.0  5.0  1