# Numpy

Data structure for Numpy is Array

In [3]:
#importing numpy
import numpy as np

In [4]:
#array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#array of 10 fives
np.ones(10) * 5
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
#array of integers from 10to 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
#array of even integers from 10 to 50
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
#array of odd integers from 10to 50
np.arange(11, 51, 2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [10]:
#3X3 matrix with in value ranging from 0 to 8
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#3X3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#random number between 0 to 1
np.random.rand(1) 

array([0.45435827])

In [13]:
np.random.randint(15) #random integer

9

In [14]:
#create 25 random sample from standard normal distribution
np.random.randn(25) 

array([ 1.17352074,  2.09415802,  0.36555312,  0.98696956, -0.61742263,
       -1.18113071,  0.6549551 , -2.18755197, -0.06592002, -0.80240261,
        0.6674127 , -2.03637517, -0.88269121,  2.19153265,  0.70399433,
        1.03448081, -0.14097277, -2.08937112, -2.88612392,  0.33484338,
        0.05149697,  0.92741673, -0.33181229,  0.53823913,  0.52983656])

In [15]:
np.arange(1, 101).reshape(10, 10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [16]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [17]:
#20 linearly spaced points between 0 and 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection


In [18]:
mat = np.arange(0, 25).reshape(5, 5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
#indexing a[row][column]
mat[4][2] #5th row 3rd column as index start from 0 

22

In [20]:
#selecting [from : to: step] index start at from ans stop at to-1
mat[0:3, 0:4:2]

array([[ 0,  2],
       [ 5,  7],
       [10, 12]])

In [21]:
#sum of value in matrix
mat.sum()

300

In [22]:
#standard deviation of mat
np.std(mat)

7.211102550927978

In [23]:
#sum of row of mat
mat.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [24]:
#sum of column of mat
mat.sum(axis = 0)

array([50, 55, 60, 65, 70])

# Pandas and DataFrame

Data structure for Pandas is Dataframe

In [25]:
import pandas as pd
import numpy as np

In [26]:
# creating dataframe using random number => np.random.rand(shape) and 
# assigning index for dataframe
df = pd.DataFrame(np.random.randn(5, 5), [1, 2, 3, 4, 5], ['A', 'B', 'C', 'D', 'E'])
df

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
2  0.313903  1.260159  2.079102 -0.777391 -0.475109
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101
4  0.764665  2.760535 -1.292100  0.030631  0.783454
5 -0.485855  0.353787 -0.949419 -0.659140  0.911442

In [27]:
#acessing or assigning different colums of dataframe
new_df = df['A']
new_df

1    1.861483
2    0.313903
3   -0.782328
4    0.764665
5   -0.485855
Name: A, dtype: float64

In [28]:
#new data frame with 2 columns of df
new_df1 = df[['A', 'C']]
new_df1

A         C
1  1.861483 -0.591441
2  0.313903  2.079102
3 -0.782328 -0.498084
4  0.764665 -1.292100
5 -0.485855 -0.949419

In [29]:
#adding new column 
df['total'] = df['A'] + df['B'] + df['C'] + df['D'] + df['E']

In [30]:
df

A         B         C         D         E     total
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431  0.052200
2  0.313903  1.260159  2.079102 -0.777391 -0.475109  2.400664
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101 -0.523176
4  0.764665  2.760535 -1.292100  0.030631  0.783454  3.047183
5 -0.485855  0.353787 -0.949419 -0.659140  0.911442 -0.829185

In [31]:
#removing column 
df.drop('total', axis = 1) # also change axis: 1 to drop column and 0 to drop row

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
2  0.313903  1.260159  2.079102 -0.777391 -0.475109
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101
4  0.764665  2.760535 -1.292100  0.030631  0.783454
5 -0.485855  0.353787 -0.949419 -0.659140  0.911442

In [32]:
df #doesnt changes on df to prevent acidently losing data so must add argument inplace = True

A         B         C         D         E     total
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431  0.052200
2  0.313903  1.260159  2.079102 -0.777391 -0.475109  2.400664
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101 -0.523176
4  0.764665  2.760535 -1.292100  0.030631  0.783454  3.047183
5 -0.485855  0.353787 -0.949419 -0.659140  0.911442 -0.829185

In [33]:
df.drop('total', axis = 1, inplace= True)

In [34]:
df #now the total column is dropped 

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
2  0.313903  1.260159  2.079102 -0.777391 -0.475109
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101
4  0.764665  2.760535 -1.292100  0.030631  0.783454
5 -0.485855  0.353787 -0.949419 -0.659140  0.911442

In [35]:
#to drop rows
df.drop(5, inplace = True) #axis not required to specify coz default is 0
df

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
2  0.313903  1.260159  2.079102 -0.777391 -0.475109
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101
4  0.764665  2.760535 -1.292100  0.030631  0.783454

In [36]:
df.shape 

(4, 5)

NOTE: Since the shape is in tuple (4, 5) where row is 4 and column is 5 so, the position of row is 0 resulting its axis as 0 similarly column as 1

In [37]:
#acessing or assigning different row of dataframe 
df.loc[1] #we pass 1 as name of index

A    1.861483
B   -1.252330
C   -0.591441
D   -1.802943
E    1.837431
Name: 1, dtype: float64

So, Both row and columns are series

In [38]:
df.iloc[0] #in iloc we have to pass index of row as argumnet

A    1.861483
B   -1.252330
C   -0.591441
D   -1.802943
E    1.837431
Name: 1, dtype: float64

In [39]:
df.loc[[1, 4]]

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
4  0.764665  2.760535 -1.292100  0.030631  0.783454

In [40]:
#acessing  different rows and column at same time
df.loc[[1, 2, 4], ['A', 'C', 'E']]

A         C         E
1  1.861483 -0.591441  1.837431
2  0.313903  2.079102 -0.475109
4  0.764665 -1.292100  0.783454

In [41]:
booldf = df>0
booldf

A      B      C      D      E
1   True  False  False  False   True
2   True   True   True  False  False
3  False   True  False  False  False
4   True   True  False   True   True

In [42]:
df[booldf]

A         B         C         D         E
1  1.861483       NaN       NaN       NaN  1.837431
2  0.313903  1.260159  2.079102       NaN       NaN
3       NaN  0.977045       NaN       NaN       NaN
4  0.764665  2.760535       NaN  0.030631  0.783454

In [43]:
# dataframe list where A is greater than 0
df[df['A']> 0]

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
2  0.313903  1.260159  2.079102 -0.777391 -0.475109
4  0.764665  2.760535 -1.292100  0.030631  0.783454

since other row in A have value less than 0 so it is not included


In [44]:
df[df['A']> 0]['B'] # now returns only needed column

1   -1.252330
2    1.260159
4    2.760535
Name: B, dtype: float64

In [45]:
df[df['A']> 0][['B', 'D']]

B         D
1 -1.252330 -1.802943
2  1.260159 -0.777391
4  2.760535  0.030631

In [46]:
#df[(df['A']> 0) and (df['A']> 0)] raise error since and can only work with single boolean value i.e. True and False
df[(df['A'] < 0) & (df['B'] < 0)]


Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [47]:
#Reseting index 
df.reset_index()

index         A         B         C         D         E
0      1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
1      2  0.313903  1.260159  2.079102 -0.777391 -0.475109
2      3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101
3      4  0.764665  2.760535 -1.292100  0.030631  0.783454

After reseting index previous index will be changed into dataframe and we can drop that previous index

In [48]:
df

A         B         C         D         E
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431
2  0.313903  1.260159  2.079102 -0.777391 -0.475109
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101
4  0.764665  2.760535 -1.292100  0.030631  0.783454

use argumemt inplace =True For permanent change

In [49]:
#creating new column in dataframe
newind = "i ii iii iv".split() 
df[''] = newind # can use variable name in '' aswell
df

A         B         C         D         E     
1  1.861483 -1.252330 -0.591441 -1.802943  1.837431    i
2  0.313903  1.260159  2.079102 -0.777391 -0.475109   ii
3 -0.782328  0.977045 -0.498084 -0.160707 -0.059101  iii
4  0.764665  2.760535 -1.292100  0.030631  0.783454   iv

In [50]:
df.set_index('') #setting new index and use inplace to make permanent changes

A         B         C         D         E
                                                     
i    1.861483 -1.252330 -0.591441 -1.802943  1.837431
ii   0.313903  1.260159  2.079102 -0.777391 -0.475109
iii -0.782328  0.977045 -0.498084 -0.160707 -0.059101
iv   0.764665  2.760535 -1.292100  0.030631  0.783454

In [51]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [52]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -1.822942  0.025840
   2 -1.051904  1.218842
   3 -1.074908 -0.831211
G2 1 -0.445328  0.454877
   2 -0.591150  0.652768
   3 -0.315391 -0.067710

# Index in multi level index dataframe

In [53]:
df.loc['G1']

A         B
1 -1.822942  0.025840
2 -1.051904  1.218842
3 -1.074908 -0.831211

In [54]:
df.loc['G1'].loc[2]

A   -1.051904
B    1.218842
Name: 2, dtype: float64

In [55]:
df.loc['G1'].loc[2]['B']

1.218842307194357

# giving name to index

In [56]:
df.index.names

FrozenList([None, None])

In [57]:
df.index.names = ['Group', 'Num']
df

A         B
Group Num                    
G1    1   -1.822942  0.025840
      2   -1.051904  1.218842
      3   -1.074908 -0.831211
G2    1   -0.445328  0.454877
      2   -0.591150  0.652768
      3   -0.315391 -0.067710

In [58]:
#another method of specifying index
df.xs('G1')

A         B
Num                    
1   -1.822942  0.025840
2   -1.051904  1.218842
3   -1.074908 -0.831211

In [59]:
df.xs(1, level = 'Num') #get all value of num = 1

A         B
Group                    
G1    -1.822942  0.025840
G2    -0.445328  0.454877

In [60]:
df.xs(2, level = 'Num')

A         B
Group                    
G1    -1.051904  1.218842
G2    -0.591150  0.652768

# Working With missing Data

In [61]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [62]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [63]:
df.dropna() #drops row of null value

A    B  C
0  1.0  5.0  1

In [64]:
df.dropna(axis = 1) #drops column of null value

C
0  1
1  2
2  3

In [65]:
df.dropna(thresh = 2) #thres = Require that many non-NA values. to drop row or col 

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [66]:
#FILL NaN
df.fillna(value = "Filled")

A       B  C
0       1       5  1
1       2  Filled  2
2  Filled  Filled  3

In [67]:
df['A'].fillna(value = df['A'].mean()) #fills na with the mean of value in that col

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [68]:
df.loc[1].fillna(value = df.loc[1].mean(), axis = 0) #axis  = 0 for selecting index i.e row 

A    2.0
B    2.0
C    2.0
Name: 1, dtype: float64

NOTE: Use .loc[] to select or fill value in row


## Group By
Allows you to group together rows based off of a column and perform an agregate function on them


In [69]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [70]:
df = pd.DataFrame(data)

In [71]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [72]:
by_company = df.groupby('Company')

In [73]:
by_company.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [74]:
by_company.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [75]:
by_company.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [76]:
by_company.sum().loc['FB'] #gives sum of specific index

Sales    593
Name: FB, dtype: int64

In [77]:
by_company.count() #number of person in company

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [78]:
by_company.max() #finding maxing sale

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [79]:
by_company.min() #finding min sale

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [80]:
df.groupby('Company').describe() #list all mean std, quartile

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [81]:
df.groupby('Company').describe().transpose() #list all mean std, quartile in transpose view

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [82]:
df.groupby('Company').describe().transpose()['FB'] # list same for FB only

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

## Merging Joining And Concatenating Dataframe

In [83]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [84]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [85]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [86]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [87]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [88]:
pd.merge(left, right, on = 'key') # how = 'inner' deafult , on = key merge on same key col they share

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

## Operation


In [89]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})


In [90]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [91]:
df['col2'].unique()

array([444, 555, 666])

In [92]:
df['col2'].nunique() #return number of unique value

3

In [93]:
df['col2'].value_counts() # how many time each unique value occured

444    2
555    1
666    1
Name: col2, dtype: int64

In [96]:
df[(df['col1']>2) & (df['col2'] == 444)] # selecting data uisng condiitonal method

col1  col2 col3
3     4   444  xyz

#### We can use apply() to work with self-built function 

In [97]:
def times2(x):
    return x*2`

In [98]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [100]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

##### Similarly we can use lamda function instead of writing whole function

In [101]:
df['col1'].apply(lambda x : x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [102]:
#drop column
df.drop('col1', axis= 1) # inlace = True for permanent change

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [105]:
df.columns #return list of index

Index(['col1', 'col2', 'col3'], dtype='object')

In [106]:
df.index #return list of index

RangeIndex(start=0, stop=4, step=1)

#### Sorting in DF

In [108]:
df.sort_values(by = 'col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [111]:
df.isnull() #find if any data is null or not

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [112]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [113]:
df.pivot_table(values = 'D', index = ['A', 'B'], columns = ['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN